# Site
url: https://samandaneshvar.github.io/613tech
title: Reliable Tech Experts - 613tech.ca
description: The best computer repair shop in Ottawa and Gatineau.
logo: assets/images/logo.svg
logo-icon: assets/images/logo-icon.svg
favicon: assets/images/favicon.png
google_analytics: xxx
disqus: demowebsite
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include: [_pages]
permalink: /:title/

# Authors
authors:
  saman:
    name: Saman
    display_name: Saman
    avatar: assets/images/saman-avatar.png
    email: saman@613tech.ca
    web: /authors/saman
    twitter: https://twitter.com/SamanDaneshvar
    description: Machine Learning, Data Science, and NLP Engineer by trade. Passionate about tech, business, and music.

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/
    
# Pagination 
paginate: 6
paginate_path: /blog/page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to enabled to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: disabled
adsense-data-ad-client: ca-pub-3412143450191416
adsense-data-ad-slot: 1363087678

# Lazy Images (enabled or disabled)
lazyimages: disabled

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
